<Project Sdk="Microsoft.NET.Sdk">
    
    <ItemGroup>
        <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.13"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4"/>
    </ItemGroup>

</Project>
