<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\EFCore.BulkExtensions.props" />

  <PropertyGroup>
    <AssemblyName>EFCore.BulkExtensions.SqlServer</AssemblyName>
    <PackageId>EFCore.BulkExtensions.MIT.SqlServer</PackageId>
    <Title>EFCore.BulkExtensions.MIT.SqlServer</Title>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EFCore.BulkExtensions.Abstractions\EFCore.BulkExtensions.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\EFCoreBulk.png" Pack="True" PackagePath="" />
    <None Include="..\..\README.md" Pack="True" PackagePath="" />
    <Content Include="..\..\LICENSE" Link="LICENSE" Pack="true" PackagePath="LICENSE" />
  </ItemGroup>

  <Import Project="..\..\targets\Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite.targets" />
  <Import Project="..\..\targets\Microsoft.EntityFrameworkCore.SqlServer.HierarchyId.targets" />

</Project>